// pkg/nft/resolve_test.go
package nft_test

import (
	"context"
	"strings"
	"testing"

	"vaka.dev/vaka/pkg/nft"
	"vaka.dev/vaka/pkg/policy"
)

func TestParseResolvConf(t *testing.T) {
	input := `
# Generated by NetworkManager
domain example.com
search example.com
nameserver 8.8.8.8
nameserver 2001:4860:4860::8888
nameserver 1.1.1.1
`
	servers, err := nft.ParseResolvConf(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseResolvConf: %v", err)
	}
	if len(servers) != 3 {
		t.Fatalf("len(servers) = %d, want 3", len(servers))
	}
	if servers[0] != "8.8.8.8" {
		t.Errorf("servers[0] = %q, want 8.8.8.8", servers[0])
	}
	if servers[1] != "2001:4860:4860::8888" {
		t.Errorf("servers[1] = %q, want 2001:4860:4860::8888", servers[1])
	}
}

func TestParseResolvConfEmpty(t *testing.T) {
	_, err := nft.ParseResolvConf(strings.NewReader("# no nameservers here\n"))
	if err == nil {
		t.Fatal("expected error for empty resolv.conf, got nil")
	}
}

func TestExpandDNSRuleExplicitServers(t *testing.T) {
	rules, err := nft.ExpandDNS([]string{"8.8.8.8", "1.1.1.1"})
	if err != nil {
		t.Fatalf("ExpandDNS: %v", err)
	}
	// Expect UDP/53 and TCP/53 accept rules for each server.
	combined := strings.Join(rules, "\n")
	if !strings.Contains(combined, "ip  daddr { 8.8.8.8 } udp dport { 53 } accept") {
		t.Errorf("missing UDP/53 rule for 8.8.8.8:\n%s", combined)
	}
	if !strings.Contains(combined, "ip  daddr { 8.8.8.8 } tcp dport { 53 } accept") {
		t.Errorf("missing TCP/53 rule for 8.8.8.8:\n%s", combined)
	}
	if !strings.Contains(combined, "ip  daddr { 1.1.1.1 } udp dport { 53 } accept") {
		t.Errorf("missing UDP/53 rule for 1.1.1.1:\n%s", combined)
	}
}

func TestExpandDNSRuleIPv6Server(t *testing.T) {
	rules, err := nft.ExpandDNS([]string{"2001:4860:4860::8888"})
	if err != nil {
		t.Fatalf("ExpandDNS: %v", err)
	}
	combined := strings.Join(rules, "\n")
	if !strings.Contains(combined, "ip6 daddr { 2001:4860:4860::8888 } udp dport { 53 } accept") {
		t.Errorf("missing ip6 UDP/53 rule:\n%s", combined)
	}
}

// dns: { servers: [...] } must succeed even when resolv.conf is absent/empty.
func TestResolvePolicyExplicitServersDoNotRequireResolvConf(t *testing.T) {
	ctx := context.Background()
	e := &policy.EgressPolicy{
		DefaultAction: "reject",
		Accept: []policy.Rule{
			{DNS: &policy.DNSRule{Servers: []string{"8.8.8.8", "1.1.1.1"}}},
		},
	}
	// Pass nil resolvConf — must succeed because no rule needs resolv.conf.
	resolved, err := nft.ResolvePolicy(ctx, e, nil, &fakeResolver{})
	if err != nil {
		t.Fatalf("unexpected error with explicit dns.servers and nil resolvConf: %v", err)
	}
	if len(resolved.Accept) == 0 {
		t.Error("expected accept rules to be generated from explicit servers")
	}
}

// Mixed rules: one dns:{} (needs resolv.conf) + one dns.servers (does not).
// resolv.conf absent → fail because dns:{} still requires it.
func TestResolvePolicyMixedDNSRulesRequireResolvConf(t *testing.T) {
	ctx := context.Background()
	e := &policy.EgressPolicy{
		DefaultAction: "reject",
		Accept: []policy.Rule{
			{DNS: &policy.DNSRule{}},                             // needs resolv.conf
			{DNS: &policy.DNSRule{Servers: []string{"8.8.8.8"}}}, // does not
		},
	}
	// nil resolvConf → must error because one rule has empty servers.
	_, err := nft.ResolvePolicy(ctx, e, nil, &fakeResolver{})
	if err == nil {
		t.Fatal("expected error when dns:{} is present and resolvConf is nil")
	}
}

// No dns: rules at all → resolvConf is never accessed (can be nil).
func TestResolvePolicyNoDNSRulesSkipsResolvConf(t *testing.T) {
	ctx := context.Background()
	e := &policy.EgressPolicy{
		DefaultAction: "reject",
		Accept: []policy.Rule{
			{Proto: "tcp", To: []string{"10.0.0.1"}, Ports: []policy.PortSpec{{Single: 443}}},
		},
	}
	// nil resolvConf — must succeed because no dns: rules exist.
	_, err := nft.ResolvePolicy(ctx, e, nil, &fakeResolver{})
	if err != nil {
		t.Fatalf("unexpected error when no dns rules and nil resolvConf: %v", err)
	}
}

// fakeResolver is a no-op Resolver for tests that do not exercise DNS lookups.
type fakeResolver struct{}

func (f *fakeResolver) LookupHost(_ context.Context, host string) ([]string, error) {
	return []string{"192.0.2.1"}, nil // always return a stable test IP
}
